apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  schedule: "@daily"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 30
      template:
        spec:
          containers:
          - name: clear
            env:
            - name: LOG_LEVEL
              value: DEBUG
            image: ymian/curator:latest
          restartPolicy: Never
